spring.profiles.active=local
spring.application.name=hotelQD
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=crate-drop
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Notas:
# Se usó la configuración profiles active "local" para evitar errores de contraseña y usuarios locales distintos
#, ya que las contraseñas de una máquina local y otra son distintas para el postgres local.
