services:
  postgres:
    image: postgres:16

    container_name: hotel_postgres

    environment:
      POSTGRES_USER: monte
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: hotel_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: